theme: jekyll-theme-minimal

title: Github projects
description: My interests are version control, visualization of diffs, and practical applications of version control and diff visualization between versions of legal texts (comparing law versions).
show_downloads: false
google_analytics: false

github:
    is_user_page: true
    owner_name: Valters Vingolds
    owner_url: https://github.com/valters/
